using System;
using System.IO;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Starbound;

public static class RuleChecks {
 static int checks;
 static void Eq(object actual,object expected,string name){checks++;if(Convert.ToString(actual,System.Globalization.CultureInfo.InvariantCulture)!=Convert.ToString(expected,System.Globalization.CultureInfo.InvariantCulture))throw new Exception(name+": actual="+actual+" expected="+expected);}
 static void Near(double actual,double expected,string name){checks++;if(Math.Abs(actual-expected)>1e-7)throw new Exception(name+": actual="+actual+" expected="+expected);}
 public static int Main(string[] args){try{Run(args[0]);Console.WriteLine("PASS: "+checks+" assertions, including every recorded web battle action, defense tick, economy, duel, persistence and growth boundary.");return 0;}catch(Exception ex){Console.Error.WriteLine(ex);return 1;}}
 static void Run(string root){string catalogJson=File.ReadAllText(Path.Combine(root,"unity/StarboundPact/Assets/Resources/Data/catalog.json")),initial=File.ReadAllText(Path.Combine(root,"unity/StarboundPact/Assets/Resources/Data/initial-save.json"));var cat=JsonConvert.DeserializeObject<Catalog>(catalogJson);var fixture=JObject.Parse(File.ReadAllText(Path.Combine(root,"unity/tests/web-rule-fixtures.json")));
  for(int i=0;i<cat.companions.Length;i++){var s=Growth.Stats(cat.companions[i],cat,cat.weapons);var f=fixture["stats"][i];Near(s.hp,(double)f["hp"],"growth hp");Near(s.attack,(double)f["attack"],"growth attack");Near(s.defense,(double)f["defense"],"growth defense");}
  foreach(var path in fixture["astral"]){var b=new AstralBattle(cat.companions.Take(5),cat.weapons,cat,(string)path["path"]);foreach(var step in path["steps"]){var e=b.Act((string)step["command"]);if(e==null)throw new Exception("Action rejected");Eq(b.active,(int)step["active"],"active");Eq(b.round,(int)step["round"],"round");Near(b.bossHp,(double)step["bossHp"],"bossHp");Eq(b.points,(int)step["points"],"points");for(int i=0;i<5;i++){Near(b.units[i].hp,(double)step["hp"][i],"fighter hp");Eq(b.units[i].energy,(int)step["energy"][i],"energy");}Near(e.damage,(double)step["damage"],"direct");Near(e.pursuit,(double)step["pursuit"],"pursuit");Near(e.dot,(double)step["dot"],"dot");Near(e.healing,(double)step["healing"],"healing");}Eq(b.outcome,(string)path["outcome"],"outcome");}
  var d=new Defense();Eq(d.Deploy(cat.companions.First(c=>c.id=="alden"),2,2,3,cat,cat.weapons),true,"tank deploy");Eq(d.Deploy(cat.companions.First(c=>c.id=="selene"),3,2,3,cat,cat.weapons),true,"mage deploy");d.Start();foreach(var frame in fixture["defense"]){for(int i=0;i<30;i++)d.Tick(1.0/30);Eq(d.health,(int)frame["health"],"base health");Eq(d.kills,(int)frame["kills"],"kills");Eq(d.phase,(string)frame["phase"],"defense phase");Near(d.dp,(double)frame["dp"],"dp");Eq(d.operators.Count,frame["ops"].Count(),"operators");for(int i=0;i<d.operators.Count;i++)Near(d.operators[i].hp,(double)frame["ops"][i]["hp"],"operator hp");Eq(d.enemies.Count,frame["enemies"].Count(),"enemies");for(int i=0;i<d.enemies.Count;i++){Near(d.enemies[i].hp,(double)frame["enemies"][i]["hp"],"enemy hp");Near(d.enemies[i].progress,(double)frame["enemies"][i]["progress"],"enemy progress");}}
  var w=new War(cat);w.shop=Enumerable.Repeat("alden",5).ToArray();w.Buy(0);w.Buy(1);w.Buy(2);w.Move(w.roster[0],"front");w.Fight(cat.companions);var wf=fixture["war"];Eq(w.gold,(int)wf["gold"],"war gold");Eq(w.health,(int)wf["health"],"war health");Eq(w.phase,(string)wf["phase"],"war phase");Eq(w.roster[0].rank,(int)wf["rank"],"three combine");
  var duel=new Duel(cat.companions.Take(5).ToList(),cat.companions.Skip(1).Take(5).ToList(),cat,cat.weapons);foreach(var step in fixture["duel"]){duel.Act((string)step["actor"],(string)step["target"],true);Eq(duel.team,(int)step["team"],"duel team");Eq(duel.round,(int)step["round"],"duel round");for(int i=0;i<10;i++)Near(duel.fighters[i].hp,(double)step["hp"][i],"duel hp");}
  string saveDir=Path.Combine(root,"tmp/unity-check/save-tests-"+Guid.NewGuid().ToString("N"));var game=new GameSession(catalogJson,initial,saveDir);game.save.gold=0;int level=game.Character("lumi").level;game.Level("lumi");Eq(game.Character("lumi").level,level,"no free upgrade");game.save.gold=800;game.Level("lumi");Eq(game.Character("lumi").level,level+1,"upgrade");Eq(game.save.gold,400,"upgrade cost");game.Equip("lumi","w-light");Eq(game.save.weapons.Count(v=>v.ownerId=="lumi"),1,"one weapon slot");game.save.crystals=160;game.save.pityLimited=79;game.save.limitedGuaranteed=true;var pull=game.Summon("limited",1);Eq(pull[0].id,"astra","limited guarantee");Eq(game.save.pityLimited,0,"reset pity");Eq(game.save.crystals,0,"pull cost");Eq(game.Summon("limited",1).Count,0,"insufficient crystals");game.save.crystals=160;game.save.materials["ring:lumi:0:pity"]=29;game.PullRing("lumi",0);Eq(game.Material("ring:lumi:0"),1,"ring guarantee");game.Ring("lumi",0,true);Eq(game.Character("lumi").rings[0],"exclusive-7","equip ring");
  game.Store();var reloaded=new GameSession(catalogJson,initial,saveDir);Eq(reloaded.Character("lumi").level,level+1,"persist growth");Eq(reloaded.Character("lumi").rings[0],"exclusive-7","persist ring");Eq(reloaded.save.weapons.Count(v=>v.ownerId=="lumi"),1,"persist equipment");var chest=cat.milestones["daily"].Last();int money=game.save.crystals;game.save.dailyActivity=0;game.ClaimChest("daily",chest);Eq(game.save.crystals,money,"locked chest cannot claim");game.save.dailyActivity=100;game.ClaimChest("daily",chest);int claimed=game.save.crystals;game.ClaimChest("daily",chest);Eq(game.save.crystals,claimed,"no double chest");
  var boundary=new Defense();Eq(boundary.Deploy(cat.companions[1],0,2,0,cat,cat.weapons),false,"entrance protected");Eq(boundary.Deploy(cat.companions[1],1,1,0,cat,cat.weapons),false,"ground restriction");boundary.Deploy(cat.companions[1],1,2,0,cat,cat.weapons);boundary.Retreat("alden");Eq(boundary.Deploy(cat.companions[1],1,2,0,cat,cat.weapons),false,"redeploy cooldown");
 }
}
